name: Markdown-To-Z-Blog
on:
  push:
    branches:
      # - main
      - test-*
    # paths:
    #   - '_posts/**'
jobs:
  post:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # Install deps - pipenv in Docker
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      # Get Post Changes
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      # List all changed files
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      # Post To Z-BlogPHP - pipenv in Docker
      - name: Post
        env:
          API_USR: ${{ secrets.API_USR }}
          API_PWD: ${{ secrets.API_PWD }}
          API_URL: ${{ secrets.API_URL }}
          IMG_HOST: ${{ secrets.IMG_HOST }}
          GIT_REPO: ${{ github.repository }}
          _cache_logs: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run post
      # Commit Changes To Git
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git diff-index --quiet HEAD || (git commit -m "Auto Commit" -a --no-verify)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
